data:
  image: busybox:latest
  container_name: data
  volumes:
    - ./:/app
  entrypoint: tail -f /dev/null

app:
  build: docker/php
  container_name: app
  working_dir: /app
  volumes_from:
    - data
  expose:
    - 9000
  links:
    - db
    - mailcatcher
  environment:
    XDEBUG_CONFIG: "idekey=PHPSTORM remote_enable=On remote_connect_back=On"

nginx:
  image: nginx:latest
  container_name: nginx
  ports:
    - "80:80"
  volumes:
    - ./:/app
    - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
  links:
    - app

mailcatcher:
    image: schickling/mailcatcher:latest
    container_name: mailcatcher
    ports:
      - "1080:1080"

db:
  image: mysql:5.7
  container_name: db
  volumes:
    - /var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: app-publishing-service
    MYSQL_USER: aps_dbu
    MYSQL_PASSWORD: aps_pass
